### ISSUE TITLE
Add support for SMTP clients (MSA)

### ISSUE THREAD

**Issue by pbeckmann** [namsral/multipass#11]
Hello, 

i want to use multipass in conjunction with caddy.

But i prefer to send the mails with nullmailer (a sendmail alternative). Cause on my servers it's already configured to send the mails via a real smtp server.

Is there a possibility to configure multipass for this?

Greetings

**Comment by namsral** [comment]
Not yet, but this sounds like a good addition.

Currently Multipass supports MTA's using the [gomail][0] package. With the same package MSA's like nullmailer and sendmail can be supported with the `Message.WriteTo` method from the same package.

```go
m := gomail.NewMessage()
cmd := exec.Command("/usr/sbin/sendmail", "-t")
cmd.Stdout, cmd.Stderr = os.Stdout, os.Stderr
w, err := cmd.StdinPipe()
if err != nil {
	return
}
err = cmd.Start()
if err != nil {
	return
}
m.WriteTo(w)
w.Close()
cmd.Wait()
}
```

Thinking out loud for the configuration syntax:

```
multipass {
    ...
    smtp_cmd /usr/bin/sendmail -t
    mail_from "Multipass <no-reply@dallas>"
}
```

[0]: https://github.com/go-gomail/gomail

**Comment by pbeckmann** [comment]
Hey,

thanks for the fast response.

I think it would be easier to put the smtp_cmd argument in _"_ as it should be easier to parse.

But all in all i would really appreciate this functionality.

Secondly it could help you with the issue #8 :D 

Greetings

**Comment by namsral** [comment]
The new SMTP client feature can also be helpful for testing mail message output.

To dump login URL requests in your home directory; create a new shell script, make it executable and add it to your configuration:

```sh
#!/usr/bin/env bash
set -e
cat <&0 > $HOME/$(date +%s).eml
```
