### ISSUE TITLE
Content-Type header missing on basepath

### ISSUE THREAD

**Issue by fanningert** [namsral/multipass#16]
Hi when I actvate multipass without GZIP everthing is working.
When I add following GZIP parameter into the config, I get a file download popup for multipass path.
```
gzip {
  level 6
}
```
only solution is currently to add the multipass path to except path for gzip.
```
gzip {
  level 6
  not /multipass
}
```

**Comment by namsral** [comment]
I can confirm that this is an bug. The Content-Type header isn't set in [multipass.go#L185](https://github.com/namsral/multipass/blob/master/multipass.go#L185)
