### ISSUE TITLE
Default helo is localhost

### ISSUE THREAD

**Issue by p-rintz** [namsral/multipass#20]
From what I can see the default helo that gomail sends out is "localhost" and multipass has no option to change this. This makes sending email over smtp fail if the server requires a correct FQDN.

` <localhost>: Helo command rejected: need fully-qualified hostname`

**Comment by namsral** [comment]
I am considering removing support for SMTP/MTA altogether and go with supporting only mail clients. MSA support was requested in #11 and added in 99ad323.

Implementing a correct MTA requires managing and queueing mail which is outside the scope of this project.

**Comment by p-rintz** [comment]
In that case, Id appreciate if the documentation could be updated for that. Because for a layman like me its not entirely clear how the feature should work now :+1:

**Comment by namsral** [comment]
The smtp_client feature is documented in the `README.md` file. The example uses the `sendmail` command which is available on most *nix systems.
